routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('login');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/importarReservas', 'ImportBookingsController@index')->name('importarReservas');

Route::post('/importFile', 'ImportBookingsController@importingFile')->name('importFile');

Route::get('/minhaImportacao', 'ImportBookingsController@myImportIndex')->name('minhaImportacao');

Route::post('/minhaImportacaoData', 'ImportBookingsController@listMyImport' )->name('minhaImportacaoData');

Route::post('/listData', 'ListController@listBookings' )->name('listData');

Route::delete('/cancelImport', 'ImportBookingsController@cancelImport' );

Route::put('/validateImport', 'ImportBookingsController@validateImport' );

Route::resource('/bookings', 'BookingsController');
Route::resource('hotel', 'HotelController');
Route::post('/hotelSearch','HotelController@hotelSearch')->name('hotelSearch');

Route::get('/lista', 'ListController@index')->name('lista');

Route::get('/reset', 'ImportBookingsController@resetDatabase')->name('reset');

Route::post('/fetchhistory','BookingsController@fetchHitstory')->name('fetchhistory');

Route::get('/exportImportData',
    [
        'as' => 'exportImport',
        'uses' => 'ImportBookingsController@excelExport'
    ]);

Route::get('/exportImportDataXML',
    [
        'as' => 'exportImportXML',
        'uses' => 'ImportBookingsController@xmlExport'
    ]);

Route::post('/removeClient', 'BookingsController@removeClient')->name('removeClient');

Route::post('/removeRoom', 'BookingsController@removeRoom')->name('removeRoom');

app/Hotel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Hotel extends Model
{
    public $fillable=['code','name','email','guide_id','location_id','transfer_price_mod','active'];
    public $timestamps = false;
    public $table='hotels';
    public function guides()
    {
        return $this->hasOne(Guide::class);
    }
    public function locate()
    {
        return $this->hasOne(Location::class);
    }

}

app/Http/Controllers/HotelController.php
<?php

namespace App\Http\Controllers;

use App\Hotel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;

class HotelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $guide = DB::table('guides')->pluck('name','id');
        $location=DB::table('locations')->pluck('name','id');
        $hotels = Hotel::orderBy('id','desc')->get();
        return view('reservas.hotel.index', compact('hotels','guide','location'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $guide = DB::table('guides')->pluck('name','id');
        $location=DB::table('locations')->pluck('name','id');
        return view('reservas.hotel.create',compact('guide','location'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Hotel::create($request -> all());
        return redirect()->route('hotel.index')->with('success-message', "You are successfully add record!");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $hotel = Hotel::findOrFail($id);
        $guide = DB::table('guides')->pluck('name','id');
        $location=DB::table('locations')->pluck('name','id');
        return view('reservas.hotel.edit', compact('hotel','guide','location'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $task = Hotel::findOrFail($id);

        $this->validate($request, [
            'code' => 'required',
            'name' => 'required',
            'email' => 'required',
            'transfer_price_mod' => 'required',
            'active' => 'required'
        ]);

        $input = $request->all();

        $task->fill($input)->save();

//        Session::flash ( 'success-message', "You are successfully updated record!" );

//        return redirect()->back();

        return redirect()->route('hotel.index')->with('success-message', "You are successfully updated record!");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (is_array($id))
        {
            Hotel::destroy($id);
        }
        else
        {
            Hotel::findOrFail($id)->delete();
        }
        return redirect()->route('hotel.index')->with('fail-message', "You are successfully delete record!");
    }
    public function hotelSearch(Request $request){
        $hotels = Hotel::where('name','like','%'.$request->name.'%')->get();
        return view('reservas.hotel.index',compact('hotels'));
    }
}

resources/views/reservas/hotel/create.blade.php
@extends('layouts.app')

@section('content')
<title>Hotel | Create</title>
    <div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">

        @if ((Session::has('success-message')))
            <div class="alert alert-success col-md-12">{{
					Session::get('success-message') }}</div>
        @endif @if ((Session::has('fail-message')))
            <div class="alert alert-danger col-md-12">{{
					Session::get('fail-message') }}</div>
        @endif
            <form action="{{route('hotel.store')}}" method="post">
                {{csrf_field()}}
                <div class="form-group">
                    <label class="control-label">CODE</label>
                    <input type="text" class="form-control" id="code" name="code" placeholder="ENTER CODIGO HERE.." required>
                </div>
                <div class="form-group">
                    <label class="control-label">NAME</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="ENTER NAME HERE.." required>
                </div>
                <div class="form-group">
                    <label class="control-label">EMAIL</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com" required>
                </div>

                <div class="form-group">
                    {{ Form::label('guide_id', 'GUIDE') }}
                    {{ Form::select('guide_id', $guide, null, ['class' => 'form-control','placeholder'=>'Select Guide', 'required'=>'']) }}
                </div>
                <div class="form-group">
                    {{ Form::label('location_id', 'LOCATION') }}
                    {{ Form::select('location_id', $location, null, ['class' => 'form-control','placeholder'=>'Select Location', 'required'=>'']) }}
                </div>
                <div class="form-group">
                    <label class="control-label">TRANSFER PRICE</label>
                    <input type="number" class="form-control" id="transfer_price_mod" name="transfer_price_mod" placeholder="ENTER PRICE HERE.." required>
                </div>
                <div class="form-group">
                    <label class="radio-inline"><input type="radio" name="active" value="1" required> ACTIVE</label>
                    <label class="radio-inline"><input type="radio" name="active" value="0"> INACTIVE</label>
                </div>
                <button type="submit" class="btn btn-success">Submit</button>
                <a href="{{route('hotel.index')}}" id="cancel" name="cancel" class="btn btn-danger">Cancel</a>

            </form>
        </div>
    </div>
    </div>
    <br>
    @endsection

resources/views/reservas/hotel/edit.blade.php
@extends('layouts.app')

@section('content')
    <title>Hotel | Edit</title>
    <div class="container">
        <div class="row">

            <div class="col-md-2"></div>
        <div class="col-md-8">

        @if ((Session::has('success-message')))
            <div class="alert alert-success col-md-12">{{
					Session::get('success-message') }}</div>
        @endif @if ((Session::has('fail-message')))
            <div class="alert alert-danger col-md-12">{{
					Session::get('fail-message') }}</div>
        @endif
                    {!! Form::model($hotel,['route' => ['hotel.update',$hotel->id], 'method' => 'PUT', 'files' => true]) !!}
                    <div class="form-group">
                        {{ Form::label('code', 'CODE') }}
                        {{ Form::text('code', null, array('class' => 'form-control','required'=>'')) }}
                    </div>
                    <div class="form-group">
                        {{ Form::label('name', 'NAME') }}
                        {{ Form::text('name', null, array('class' => 'form-control','required'=>'')) }}
                    </div>

                    <div class="form-group">
                        {{ Form::label('email', 'EMAIL') }}
                        {{ Form::email('email', null, array('class' => 'form-control', 'required'=>'')) }}
                    </div>
                    <div class="form-group">
                        {{ Form::label('guide_id', 'GUIDE') }}
                        {{ Form::select('guide_id', $guide, null, ['class' => 'form-control','placeholder'=>'Select Guide', 'required'=>'']) }}
                    </div>
                    <div class="form-group">
                        {{ Form::label('location_id', 'LOCATION') }}
                        {{ Form::select('location_id', $location, null, ['class' => 'form-control','placeholder'=>'Select Location', 'required'=>'']) }}
                    </div>

                    <div class="form-group">
                        {{ Form::label('transfer_price_mod', 'TRANSFER PRICE') }}
                        {{ Form::text('transfer_price_mod', null, array('class' => 'form-control','required'=>'')) }}
                    </div>
                    <div class="form-group">
                        <label class="radio-inline"><input type="radio" name="active" value="1" required> ACTIVE</label>
                        <label class="radio-inline"><input type="radio" name="active" value="0"> INACTIVE</label>
                    </div>
                    {{ Form::submit('Update', array('class' => 'btn btn-success')) }}
            <a href="{{route('hotel.index')}}" id="cancel" name="cancel" class="btn btn-danger">Cancel</a>

            {!! Form::close() !!}



    </div>
        </div>
    </div>
    <br>

@endsection

resources/views/reservas/hotel/index.blade.php
@extends('layouts.app')

@section('content')
    <title>Hotel | View</title>

<div class="container">
    @if ((Session::has('success-message')))
        <div class="alert alert-success col-md-12">{{
					Session::get('success-message') }}</div>
    @endif @if ((Session::has('fail-message')))
        <div class="alert alert-danger col-md-12">{{
					Session::get('fail-message') }}</div>
    @endif
        <div class="container">
        <div class="row">
        <div class="col-md-3">
            <a href="{{route('hotel.create')}}" id="cancel" name="cancel" class="btn btn-success">Add New Hotel</a>

        </div>
            <div class="col-md-6"></div>
                <div class="col-md-3">

            <div class="agileits_search">
            <form action="{{route('hotelSearch')}}" method="POST">
                {{csrf_field()}}
                <input name="name" type="search" placeholder="Search hotel name" required="">
                <button type="submit" class="btn btn-success" aria-label="Left Align">
                    <span class="fa fa-search" aria-hidden="true"> </span>
                </button>
            </form>
        </div>
                </div>
        </div>
        </div>
<div class="table-responsive" style="overflow: auto; height: 500px">
    <table class="table">
        <thead>
        <tr class="active">
            <th scope="col">ID</th>
            <th scope="col">CODIGO</th>
            <th scope="col">NAME</th>
            <th scope="col">EMAIL</th>
            <th scope="col">GUIDE</th>
            <th scope="col">LOCATION</th>
            {{--<th scope="col">PRICE</th>--}}
            {{--<th scope="col">STATUS</th>--}}
            <th scope="col">ACTION</th>
        </tr>
        </thead>
        <tbody>
        @forelse($hotels as $hotel)

            <tr>
            <th scope="row">{{$hotel->id}}</th>
            <td>{{$hotel->code}}</td>
            <td>{{$hotel->name}}</td>
            <td>{{$hotel->email}}</td>
            <td>{{$hotel->guide_id}}</td>
            <td>{{$hotel->location_id}}</td>
            {{--<td>{{$hotel->transfer_price_mod}}</td>--}}
                     {{--@if($hotel->active==1)--}}
                    {{--<td><span class="label-default label label-success">Active</span></td>--}}
                    {{--@else--}}
                    {{--<td><span class="label-default label label-danger">Inactive</span></td>--}}
                    {{--@endif--}}
            <td>
                <form action="{{route('hotel.destroy',$hotel->id)}}"  method="POST">
                    {{csrf_field()}}
                    {{method_field('DELETE')}}
                    <button type="submit" class="btn btn-sm btn-danger "><i class="fa fa-remove" style="font-size: 15px;"></i></button>
                </form>
                <a href="{{route('hotel.edit',$hotel->id)}}" class="btn btn-sm btn-success "><i class="fa fa-edit" style="font-size: 11px;"></i></a>

            </td>
        </tr>
        @empty
        @endforelse
        </tbody>
    </table>
</div>
</div>
@endsection