routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('login');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/importarReservas', 'ImportBookingsController@index')->name('importarReservas');

Route::post('/importFile', 'ImportBookingsController@importingFile')->name('importFile');

Route::get('/minhaImportacao', 'ImportBookingsController@myImportIndex')->name('minhaImportacao');

Route::post('/minhaImportacaoData', 'ImportBookingsController@listMyImport' )->name('minhaImportacaoData');

Route::post('/listData', 'ListController@listBookings' )->name('listData');

Route::delete('/cancelImport', 'ImportBookingsController@cancelImport' );

Route::put('/validateImport', 'ImportBookingsController@validateImport' );

Route::resource('/bookings', 'BookingsController');
Route::resource('hotel', 'HotelController');
Route::post('/hotelSearch','HotelController@hotelSearch')->name('hotelSearch');

Route::get('/lista', 'ListController@index')->name('lista');

Route::get('/reset', 'ImportBookingsController@resetDatabase')->name('reset');

Route::post('/fetchhistory','BookingsController@fetchHitstory')->name('fetchhistory');

Route::get('/exportImportData',
    [
        'as' => 'exportImport',
        'uses' => 'ImportBookingsController@excelExport'
    ]);

Route::get('/exportImportDataXML',
    [
        'as' => 'exportImportXML',
        'uses' => 'ImportBookingsController@xmlExport'
    ]);

Route::post('/removeClient', 'BookingsController@removeClient')->name('removeClient');

Route::post('/removeRoom', 'BookingsController@removeRoom')->name('removeRoom');

resources/views/partial/changeBookingForm.blade.php
<form id="changeBooking" role="form" autocomplete="off" novalidate="novalidate">




    <p>Dados da Alteraçao</p>
    <div container="changeBookings" class="form-group-attached">
        <div class="row clearfix">

            <div class="col-md-3">
                <div class="form-group form-group-default ">
                    <label>TOM</label>
                    <input type="text" class="form-control" id="historytom" name="historytom"  >
                </div>
            </div>

            <div class="col-md-2">
                <div class="form-group form-group-default ">
                    <label>Nº Reserva</label>
                    <input type="text" class="form-control" id="historynumber" name="historynumber" 
                           >
                </div>
            </div>

            <div class="col-md-3">
                <div class="form-group form-group-default ">
                    <label>Data da Reserva</label>
                    <input type="text" class="form-control dateMask" id="historydate" name="book_date"
                            >
                </div>
            </div>

            <div class="col-md-2">

                <div class="form-group form-group-default form-group-default-select2 ">
                    <label class="">Estado</label>
                    <select id="historystate" name="historystate" class="full-width initSelect2" >
                        <option value=""></option>
                        <option value="BU">BU</option>
                        <option value="UN">UN</option>
                        <option value="US">US</option>
                        <option value="ST">ST</option>

                    </select>
                </div>


            </div>

            <div class="col-md-2">

                <div class="form-group form-group-default form-group-default-select2 ">
                    <label class="">Transfer</label>
                    <select id="historyTransfer" name="historyTransfer" class="full-width initSelect2" >
                        <option value="Naotem">Não Tem</option>
                        <option value="IN">IN</option>
                        <option value="OUT">OUT</option>
                        <option value="IN+OUT">IN+OUT</option>
                        <option value="Verificar">Verificar</option>

                    </select>
                </div>


            </div>


        </div>





    </div>




    <p class="m-t-10">Dados do Clients</p>
    <div container="historyClients" rid="" id="historyClientContainer" class="form-group-attached">
        <div class="row clearfix">
            <div class="col-md-12">
                <div class="form-group form-group-default ">
                    <label>Nome</label>
                    <input type="text" class="form-control " id="historyClient" name="historyClient"  >
                </div>
            </div>
        </div>

        <div class="row clearfix">

            <div class="col-md-2">
                <div class="form-group form-group-default ">
                    <label>Idade</label>
                    <input type="text" class="form-control " id="historyAge" name="historyAge"  >
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group form-group-default ">
                    <label>Gênero</label>
                    <input type="text" class="form-control " id="historyGender" name="historyGender"  >
                </div>
            </div>


        </div>


    </div>




    <p class="m-t-10">Dados do Voo</p>
    <div container="historyflights" rid="" id="historyflights" class="form-group-attached">
        <div class="row ">
            <div class="col-md-3">
                <div class="form-group form-group-default ">
                    <label>Chegada</label>
                    <input type="text" class="form-control dateMask" id="historydepartureDate" name="historydepartureDate"  >
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group form-group-default ">
                    <label>Voo </label>
                    <input type="text" class="form-control" id="historyarrivalFlight" name="historyarrivalFlight"  >
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group form-group-default ">
                    <label>Hora</label>
                    <input type="text" class="form-control timeMask" id="historytime" name="historytime"  >
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group form-group-default ">
                    <label>Destino</label>
                    <input type="text" class="form-control" id="historyarrivalLocation" name="historyarrivalLocation" 
                           >
                </div>
            </div>

        </div>
        <div class="row clearfix">
            <div class="col-md-3">
                <div class="form-group form-group-default ">
                    <label>Partida</label>
                    <input type="text" class="form-control dateMask" id="historyarrivalDate" name="historyarrivalDate"  >
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group form-group-default ">
                    <label>Voo</label>
                    <input type="text" class="form-control" id="historydepartureFlight" name="historydepartureFlight"  >
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group form-group-default ">
                    <label>Hora</label>
                    <input type="text" class="form-control timeMask" id="historydepartureTime" name="historydepartureTime" 
                           >
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group form-group-default ">
                    <label>Local</label>
                    <input type="text" class="form-control" id="historyDestiny" name="historyDestiny" 
                           >
                </div>
            </div>

        </div>


    </div>



       <p class="m-t-10">Quartos </p>
        <div class="form-group-attached">
            <div class="row clearfix">
                <div class="col-md-3">
                    <div class="form-group form-group-default ">
                        <label>Hotel</label>
                        <input type="text" class="form-control" id="historyHotel" name="historyHotel" 
                               >
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group form-group-default ">
                        <label>Cód Hotel</label>
                        <input type="text" class="form-control" id="historyHotelCode" name="historyHotelCode" 
                               >
                    </div>
                </div>



                <div class="col-md-2">
                    <div class="form-group form-group-default ">
                        <label>Cód Quarto</label>
                        <input type="text" class="form-control" id="historyRoomCode" name="historyRoomCode" 
                               >
                    </div>
                </div>






            </div>


<div class="row">

    <div class="col-md-5">
        <div class="form-group form-group-default ">
            <label>Quarto</label>
            <input type="text" class="form-control" id="historyRoom" name="historyRoom" 
                   >
        </div>
    </div>

    <div class="col-md-2">
        <div class="form-group form-group-default ">
            <label>Noites</label>
            <input type="text" class="form-control" id="historyNights" name="historyNights" 
                   >
        </div>
    </div>



</div>

            <div class="row clearfix">

                <div class="col-md-3">
                    <div class="form-group form-group-default ">
                        <label>Checkin</label>
                        <input type="text" class="form-control" id="historyCheckIn" name="historyCheckIn" 
                               >
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="form-group form-group-default ">
                        <label>Checkout</label>
                        <input type="text" class="form-control" id="historyCheckOut" name="historyCheckOut" 
                               >
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group form-group-default ">
                        <label>Valor</label>
                        <input type="text" class="form-control" id="historyValue" name="historyValue" 
                               >
                    </div>
                </div>



            </div>

            <div class="row">

                <div class="col-md-2">
                    <div class="form-group form-group-default ">
                        <label>Dia</label>
                        <input type="text" class="form-control" id="historyDay" name="historyDay" 
                               >
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group form-group-default ">
                        <label>Qtd Quartos</label>
                        <input type="text" class="form-control" id="historyRoomsQty" name="historyRoomsQty" 
                               >
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group form-group-default ">
                        <label>Membros</label>
                        <input type="text" class="form-control" id="historyMembers" name="historyMembers" 
                               >
                    </div>
                </div>

            </div>

        </div>




    <p class="m-t-10">OBS</p>
    <div container="historyObs" class="form-group-attached">

        <div class="row">
            <div class="col-md-8">
                <div class="form-group form-group-default ">
                    <label>OBS</label>

                    <textarea id="historyNotes" class="form-control" rows="5">
                                        </textarea>
                </div>
            </div>
        </div>

    </div>
    <br>


</form>



{{--<div class="col-md-9">--}}
    {{--<button class="btn btn-danger" onclick="updateBooking()" type="button">Gravar</button>--}}
    {{--<button class="btn btn-default"  data-dismiss="modal"> Fechar</button>--}}
{{--</div>--}}

resources/views/partial/editBookingForm.blade.php
<form id="editBooking" role="form" class="frm"  autocomplete="off" novalidate="novalidate">



    <p>Dados da Reserva</p>
    <div container="bookings" class="form-group-attached">
        <div class="row clearfix">
            <div class="col-md-3">
                <div class="form-group form-group-default form-group-default-select2 ">
                    <label class="">TOM</label>
                    <select id="tms_id" name="tms_id" class="form-control full-width initSelect2" >
                        <option value="0"></option>
                        @foreach($tomOptions as $tomOption)
                            <option value="{{ trim($tomOption->id) }}">
                                {{ trim($tomOption->text) }}
                            </option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group form-group-default ">
                    <label>Nº Reserva</label>
                    <input type="text" class="form-control" id="booking" name="book_number" 
                           >
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group form-group-default ">
                    <label>Data da Reserva</label>
                    <input type="text" class="form-control dateMask" id="bookingdate" name="book_date"
                            >
                </div>
            </div>
            <div class="col-md-2">

                <div class="form-group form-group-default form-group-default-select2 ">
                    <label class="">Estado</label>
                    <select id="state" name="state" class="full-width initSelect2" >
                        <option value=""></option>
                        <option value="BU">BU</option>
                        <option value="UN">UN</option>
                        <option value="US">US</option>
                        <option value="ST">ST</option>

                    </select>
                </div>


            </div>

            <div class="col-md-2">

                <div class="form-group form-group-default form-group-default-select2 ">
                    <label class="">Transfer</label>
                    <select id="transfer" name="transfer" class="full-width initSelect2" >
                        <option value="NaoTem">Não Tem</option>
                        <option value="IN">IN</option>
                        <option value="OUT">OUT</option>
                        <option value="IN+OUT">IN+OUT</option>
                        <option value="Verificar">Verificar</option>
                    </select>
                </div>


            </div>


        </div>


    </div>
    <p class="m-t-10">Dados do Cliente  <a id="addClient" onclick="$('#addClientModal').modal();" class="fa fs-16 fa-plus-circle text-danger m-r-10"></a> </p>


    <div id="clientContainer" container="clients" class="form-group-attached">


    </div>


    <p class="m-t-10">Dados do Voo</p>
    <div container="flights" rid="" id="flights" class="form-group-attached">





        <div class="row ">
            <div class="col-md-3">
                <div class="form-group form-group-default ">
                    <label>Chegada</label>
                    <input type="text" class="form-control dateMask" id="arrivalDate" name="arrival_date"  >
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group form-group-default ">
                    <label>Voo </label>
                    <input type="text" class="form-control" id="arrivalFlight" name="arrival_flight"  >
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group form-group-default ">
                    <label>Hora</label>
                    <input type="text" class="form-control timeMask" id="time" name="arrival_time"  >
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group form-group-default ">
                    <label>Dia</label>
                    <input type="text" class="form-control" id="day" name="day" disabled >
                </div>
            </div>




        </div>

        <div class="row clearfix">
            <div class="col-md-3">
                <div class="form-group form-group-default ">
                    <label>Partida</label>
                    <input type="text" class="form-control dateMask" id="departureDate" name="departure_date"  >
                </div>
            </div>

            <div class="col-md-2">
                <div class="form-group form-group-default ">
                    <label>Voo</label>
                    <input type="text" class="form-control" id="departureFlight" name="departure_flight"  >
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group form-group-default ">
                    <label>Hora</label>
                    <input type="text" class="form-control timeMask" id="departureTime" name="departure_time" 
                           >
                </div>
            </div>

            <div class="col-md-2">
                <div class="form-group form-group-default ">
                    <label>Destino</label>
                    <input type="text" class="form-control" id="destiny" name="departure_location" 
                           >
                </div>
            </div>
        </div>


    </div>

    <!--    <p class="m-t-10">Dados da Hotel</p>
        <div class="form-group-attached">
            <div class="row clearfix">
                <div class="col-md-5">
                    <div class="form-group form-group-default ">
                        <label>Hotel</label>
                        <input type="text" class="form-control" id="hotel" name="hotel" 
                               >
                    </div>
                </div>
                <div class="col-md-1">
                    <div class="form-group form-group-default ">
                        <label>Essen</label>
                        <input type="text" class="form-control" id="essen" name="essen" 
                               >
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group form-group-default ">

                    </div>
                </div>


            </div>
        </div>
        -->


    <p class="m-t-10">Quartos  <a id="addRoom" onclick="$('#addRoomModal').modal();" class="fa fs-16 fa-plus-circle text-danger m-r-10"></a> </p>
    <div id="roomContainer" class="">

    </div>


    <p class="m-t-10">Pacotes  <a id="addPackage" onclick="$('#addPackageModal').modal();" class="fa fs-16 fa-plus-circle text-danger m-r-10"></a> </p>
    <div container="packages" class="form-group-attached">
        <div class="row clearfix">
            <div class="col-md-12">
                <div class="form-group form-group-default"><label></label>
                    <input class="tagsinput custom-tag-input" type="text" value="hello World, quotes, inspiration" style="display: none;">
                    <div class="bootstrap-tagsinput" id="packagesContainer">

                        <input size="1" type="text">
                    </div>
                </div>
            </div>


        </div>
    </div>

    <p class="m-t-10">Rent-a-Car</p>
    <div container="car" class="form-group-attached">

        <div class="row clearfix">

            <div class="col-md-2">


                <div class="form-group form-group-default form-group-default-select2 ">
                    <label class="">Tip. Auto</label>
                    <select id="type" name="type" class="full-width initSelect2" >
                        <option value="null">Selecione...</option>
                        <option value="A">Grupo A</option>
                        <option value="B">Grupo B</option>
                        <option value="C">Grupo C</option>
                        <option value="D">Grupo D</option>
                        <option value="E">Grupo E</option>
                        <option value="MWF">Grupo F</option>
                    </select>
                </div>


            </div>

            <div class="col-md-4">
                <div class="form-group form-group-default form-group-default-select2 ">
                    <label class="">Serviço RC</label>
                    <select id="rentacar_id" name="rentacar_id" class="full-width initSelect2" >
                        <option value="null">Selecione...</option>
                        @foreach($rentacarOptions as $rentacarOption)
                            <option value="{{ trim($rentacarOption->id) }}">
                                {{ trim($rentacarOption->text) }}
                            </option>
                        @endforeach
                    </select>
                </div>
            </div>


                <div class="col-md-2">
                    <div class="form-group form-group-default " >
                        <label>Valor</label>
                        <input type="text" class="form-control" id="price" name="price">
                    </div>
                </div>


        </div>
        <div class="row">
            <div class="col-md-8">
                <div class="form-group form-group-default ">
                    <label>OBS</label>

                    <textarea id="rentACarNotes" name="notes" class="form-control" rows="5">
                                        </textarea>
                </div>
            </div>
        </div>
    </div>
    <br>


</form>


<div class="col-md-9">
    <button class="btn btn-danger" onclick="saveEditModal()" type="button">Gravar</button>
    <button class="btn btn-default"  data-dismiss="modal"> Fechar</button>
</div>

resources/views/partial/menu.blade.php
    <div class="menu-bar header-sm-height" data-pages-init='horizontal-menu' data-hide-extra-li="4">
        <a href="#" class="btn-link toggle-sidebar hidden-lg-up pg pg-close" data-toggle="horizontal-menu">
        </a>
        <ul>
            <li>
                <a href="{{ route('home') }}">Home</a>
            </li>
            <li class="">
                <a href="{{route('hotel.index')}}">Hotel</a>
            </li>

            <li>
                <a href="javascript:;"><span class="title">Reservas</span>
                    <span class=" arrow"></span></a>
                <ul class="">
                    <li class="">
                        <a href="{{ route('lista') }}">Lista</a>
                    </li>
                    <li class="">

                        @if( !empty($findImport))

                            <a href="{{ route('minhaImportacao') }}">Minha Importação</a>

                            @else

                            <a href="{{ route('importarReservas') }}">Importar Reservas</a>

                        @endif



                    </li>
                    <li class="">
                        <a href="{{ route('reset') }}">Reset de Base de Dados</a>
                    </li>

                </ul>
            </li>

            <li>
                <a href="index.html">Exportar Reservas</a>
            </li>

            <li>
                <a href="index.html">Alterar Voos</a>
            </li>

            <li>
                <a href="javascript:;"><span class="title">Gestão de Entidades</span>
                    <span class=" arrow"></span></a>
                <ul class="">

                    <li class="">
                        <a href="calendar.html">Pacotes</a>
                    </li>

                    <li class="">
                        <a href="calendar_lang.html">Guias</a>
                    </li>

                    <li class="">
                        <a href="calendar_month.html">Hotéis</a>
                    </li>

                    <li class="">
                        <a href="calendar_month.html">TMS</a>
                    </li>


                    <li class="">
                        <a href="calendar_month.html">Rent-a-Car</a>
                    </li>

                    <li class="">
                        <a href="calendar_month.html">Localidades</a>
                    </li>

                    <li class="">
                        <a href="calendar_month.html">Preis</a>
                    </li>

                    <li class="">
                        <a href="calendar_month.html">Preis HF</a>
                    </li>

                </ul>
            </li>

            <li>
                <a href="javascript:;"><span class="title">Gestão de Email</span>
                    <span class=" arrow"></span></a>
                <ul class="">
                    <li class="">
                        <a href="calendar.html">Configurações Hotéis</a>
                    </li>
                    <li class="">
                        <a href="calendar_lang.html">Configurações Rent-a-Car</a>
                    </li>
                    <li class="">
                        <a href="calendar_month.html">Caixa de Saída</a>
                    </li>

                </ul>
            </li>





        </ul>

    </div>

resources/views/partial/scripts.blade.php
<!-- BEGIN VENDOR JS -->
<script src="{{ asset ('plugins/feather-icons/feather.min.js') }}" type="text/javascript"></script>
<script src="{{ asset ('plugins/pace/pace.min.js') }}" type="text/javascript"></script>
<script src="{{ asset ('plugins/jquery/jquery-1.11.1.min.js') }}" type="text/javascript"></script>
<script src="{{ asset ('plugins/modernizr.custom.js') }}" type="text/javascript"></script>
<script src="{{ asset ('plugins/jquery-ui/jquery-ui.min.js') }}" type="text/javascript"></script>
<script src="{{ asset ('plugins/tether/js/tether.min.js') }}" type="text/javascript"></script>
<script src="{{ asset ('plugins/bootstrap/js/bootstrap.min.js') }}" type="text/javascript"></script>
<script src="{{ asset ('plugins/jquery/jquery-easy.js') }}" type="text/javascript"></script>
<script src="{{ asset ('plugins/jquery-unveil/jquery.unveil.min.js') }}" type="text/javascript"></script>
<script src="{{ asset ('plugins/jquery-ios-list/jquery.ioslist.min.js') }}" type="text/javascript"></script>
<script src="{{ asset ('plugins/jquery-actual/jquery.actual.min.js') }}"></script>
<script src="{{ asset ('plugins/jquery-scrollbar/jquery.scrollbar.min.js') }}"></script>
<script type="text/javascript" src="{{ asset ('plugins/select2/js/select2.full.min.js') }}"></script>
<script type="text/javascript" src="{{ asset ('plugins/classie/classie.js') }}"></script>
<script src="{{ asset ('plugins/switchery/js/switchery.min.js') }}" type="text/javascript"></script>
<script src="{{ asset ('plugins/jquery-validation/js/jquery.validate.min.js') }}" type="text/javascript"></script>
<script src="{{ asset ('plugins/jquery-validation/js/localization/messages_pt_PT.min.js') }}" type="text/javascript"></script>

<script src="{{ asset ('plugins/bootstrap3-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script>
<script type="text/javascript" src="{{ asset ('plugins/jquery-autonumeric/autoNumeric.js') }}"></script>

<script type="text/javascript" src="{{ asset ('plugins/bootstrap-tag/bootstrap-tagsinput.min.js') }}"></script>
<script type="text/javascript" src="{{ asset ('plugins/jquery-inputmask/jquery.inputmask.min.js') }}"></script>
<script src="{{ asset ('plugins/bootstrap-form-wizard/js/jquery.bootstrap.wizard.min.js') }}" type="text/javascript"></script>
<script src="{{ asset ('plugins/jquery-validation/js/jquery.validate.min.js') }}" type="text/javascript"></script>
<script src="{{ asset ('plugins/bootstrap-datepicker/js/bootstrap-datepicker.js') }}" type="text/javascript"></script>
<script src="{{ asset ('plugins/summernote/js/summernote.min.js') }}" type="text/javascript"></script>
<script src="{{ asset ('plugins/moment/moment.min.js') }}"></script>
<script src="{{ asset ('plugins/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
<script src="{{ asset ('plugins/bootstrap-timepicker/bootstrap-timepicker.min.js') }}"></script>
<script src="{{ asset ('plugins/bootstrap-typehead/typeahead.bundle.min.js') }}"></script>
<script src="{{ asset ('plugins/bootstrap-typehead/typeahead.jquery.min.js') }}"></script>
<script src="{{ asset ('plugins/handlebars/handlebars-v4.0.5.js') }}"></script>
<script src="{{ asset ('plugins/bootstrap-collapse/bootstrap-tabcollapse.js') }}" type="text/javascript"></script>

<!-- END VENDOR JS -->
<!-- BEGIN CORE TEMPLATE JS -->
<script src="{{ asset ('pages/js/pages.js') }}"></script>
<!-- END CORE TEMPLATE JS -->
<!-- BEGIN PAGE LEVEL JS -->
<script src="{{ asset ('js/notifications.js') }}" type="text/javascript"></script>
<script src="{{ asset ('js/scripts.js') }}" type="text/javascript"></script>
<script>
    $(document).ready(function() {

        $(".dateMask").mask("99/99/9999");
        $(".timeMask").mask("99:99");
        $('.autonumeric').autoNumeric('init');

        $('.timePicker').timepicker();
        // $('.timePicker').timepicker().on('show.timepicker', function(e) {
        //     var widget = $('.bootstrap-timepicker-widget');
        //     widget.find('.glyphicon-chevron-up').removeClass().addClass('pg-arrow_maximize');
        //     widget.find('.glyphicon-chevron-down').removeClass().addClass('pg-arrow_minimize');
        // });
    });


</script>
<!-- END PAGE LEVEL JS -->